//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leitor.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUploadFile")]
    public interface IUploadFile {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadFile/GetStatusWCF", ReplyAction="http://tempuri.org/IUploadFile/GetStatusWCFResponse")]
        void GetStatusWCF();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadFile/GetStatusWCF", ReplyAction="http://tempuri.org/IUploadFile/GetStatusWCFResponse")]
        System.Threading.Tasks.Task GetStatusWCFAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadFile/UploadZipFile", ReplyAction="http://tempuri.org/IUploadFile/UploadZipFileResponse")]
        string UploadZipFile(byte[] fileByteArray, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUploadFile/UploadZipFile", ReplyAction="http://tempuri.org/IUploadFile/UploadZipFileResponse")]
        System.Threading.Tasks.Task<string> UploadZipFileAsync(byte[] fileByteArray, string fileName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUploadFileChannel : Leitor.ServiceReference1.IUploadFile, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadFileClient : System.ServiceModel.ClientBase<Leitor.ServiceReference1.IUploadFile>, Leitor.ServiceReference1.IUploadFile {
        
        public UploadFileClient() {
        }
        
        public UploadFileClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadFileClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadFileClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadFileClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetStatusWCF() {
            base.Channel.GetStatusWCF();
        }
        
        public System.Threading.Tasks.Task GetStatusWCFAsync() {
            return base.Channel.GetStatusWCFAsync();
        }
        
        public string UploadZipFile(byte[] fileByteArray, string fileName) {
            return base.Channel.UploadZipFile(fileByteArray, fileName);
        }
        
        public System.Threading.Tasks.Task<string> UploadZipFileAsync(byte[] fileByteArray, string fileName) {
            return base.Channel.UploadZipFileAsync(fileByteArray, fileName);
        }
    }
}
